Project/Models/PublicationViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Models
{
    public class PublicationListViewModel
    {
        public PublicationListViewModel()
        {
            List = new List<Publication>();
            Header = new List<Publication>();
        }

        public int Index { get; set; }
        public Boolean HaveMore { get; set; }
        public Boolean HaveLess { get; set; }
        public List<Publication> List { get; set; }
        public List<Publication> Header { get; set; }
    }

    public class PublicationCreateViewModel
    {
        [Required(ErrorMessage = "O Título é um campo obrigatório")]
        [DisplayName("Titulo")]
        public String Name { get; set; }
        
        [DisplayName("Resumo")]
        public String Resume { get; set; }

        [Required(ErrorMessage = "A Descrição é um campo obrigatório")]
        [DisplayName("Descrição")]
        [AllowHtml]
        public String Description { get; set; }

        [DefaultValue(false)]
        [DisplayName("É um evento?")]
        public Boolean IsEvent { get; set; }

        [DisplayName("É um inquérito?")]
        [DefaultValue(false)]
        public Boolean IsPoll { get; set; }

        [DisplayName("Dia do evento")]
        public String Day { get; set; }

        [DisplayName("Local do evento")]
        public String Local { get; set; }

        [DisplayName("Questão do inquérito")]
        public String Matter { get; set; }

        [DisplayName("Os resultados serão visíveis em tempo real?")]
        [DefaultValue(false)]
        public Boolean IsVisible { get; set; }

        [DisplayName("O inquérito será disponível a Associados?")]
        [DefaultValue(false)]
        public Boolean IsInclusive { get; set; }

        [DisplayName("Link de um formulário externo")]
        [DefaultValue(null)]
        public String LinkToForm { get; set; }

        [DisplayName("Possíveis respostas ao inquérito")]
        public String[] OptionName { get; set; }
    }

    public class PublicationEditViewModel
    {
        public int ID { get; set; }
        
        [Required(ErrorMessage = "O Título é um campo obrigatório")]
        [DisplayName("Titulo")]
        public String Name { get; set; }

        [DisplayName("Imagem")]
        [DefaultValue(null)]
        public String Image { get; set; }

        [DisplayName("Resumo")]
        public String Resume { get; set; }

        [Required(ErrorMessage = "A Descrição é um campo obrigatório")]
        [DisplayName("Descrição")]
        [AllowHtml]
        public String Description { get; set; }

        [DefaultValue(false)]
        [DisplayName("É um evento?")]
        public Boolean IsEvent { get; set; }

        [DisplayName("É um inquérito?")]
        [DefaultValue(false)]
        public Boolean IsPoll { get; set; }

        [DisplayName("Dia do evento")]
        [DisplayFormat(DataFormatString = "{0:dddd, d MMM yyyy hh:mm}")]
        public DateTime? Day { get; set; }

        [DisplayName("Local do evento")]
        public String Local { get; set; }

        [DisplayName("Questão do inquérito")]
        public String Matter { get; set; }

        [DisplayName("Os resultados serão visíveis em tempo real?")]
        [DefaultValue(false)]
        public Boolean IsVisible { get; set; }

        [DisplayName("O inquérito será disponível a Associados?")]
        [DefaultValue(false)]
        public Boolean IsInclusive { get; set; }

        [DisplayName("Link de um formulário externo")]
        [DefaultValue(null)]
        public String LinkToForm { get; set; }

        [DisplayName("Possíveis respostas ao inquérito")]
        public String[] OptionName { get; set; }
    }
}

Project/Controllers/PublicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project.Models;
using Microsoft.AspNet.Identity;
using System.IO;
using System.Diagnostics;
using System.Web.UI.WebControls;

namespace Project.Controllers
{
    public class PublicationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Publications
        /// <summary>
        /// 
        /// Apresenta a lista de publicações, mas como é a primeira chamada tem um view diferente
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            try
            {
                PublicationListViewModel list = new PublicationListViewModel
                {
                    // como a view não é paginada apresenta a página a -1
                    Index = -1,
                    // como apresenta apeenas 6 publicações  verifica se o total é superior a isso
                    HaveMore = db.Publication.Count() > 6 ? true : false,
                    // como é a primeira vista da listagem de publicações, não tem uma página inferior
                    HaveLess = false, 
                    // procura as ultimas 6 publicações aceites
                    List = db.Publication.Where(x => x.Accepted).OrderByDescending(p => p.CreatedIn).Take(6).ToList(), 
                    // procura as ultimas 4 publicações com imagem para apresentar no caroussel
                    Header = db.Publication.Where(x => x.Accepted && x.Image != null).OrderByDescending(p => p.CreatedIn).Take(4).ToList()
                };
                return View(list);
            }
            catch (Exception ex)
            {
                Console.Write(ex);
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: Publications
        /// <summary>
        /// 
        /// Apresenta a lista de publicações paginadas
        /// 
        /// </summary>
        /// <param name="i"></param>
        /// <returns></returns>
        public ActionResult Page(int i)
        {
            try
            {
                // se o indice da página for -1 redireciona para o controller correspondente à primeira vista da listagem de publicações
                if (i == -1) return RedirectToAction("Index");
                // a flag servirá de auxiliar, como ponteiro ao indice das publicações a retornar
                // como esta view é dedicada apenas a listagem de publicações, já serão retornadas 9 de cada vez
                int flag = i * 9 + 6;
                PublicationListViewModel list = new PublicationListViewModel
                {
                    Index = i,
                    // se a contagem for superior ao indice desta pagina na lista de publicações mais 9 então haverá mais publicações
                    HaveMore = db.Publication.Count() > (flag + 9) ? true : false,
                    HaveLess = true,
                    List = db.Publication.Where(x => x.Accepted).OrderByDescending(p => p.CreatedIn).Skip(flag).Take(flag + 9).ToList(),
                    Header = null
                };
                return View("Index", list);
            }
            catch (Exception ex)
            {
                Console.Write(ex);
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: Publications/Profile
        /// <summary>
        /// 
        /// Procura pela publicação pretendida e envia, caso não exista retorna à pagina inicial 
        /// 
        /// </summary>
        /// <param name="publicationID"></param>
        /// <returns></returns>
        public ActionResult Details(int? publicationID)
        {
            int index = publicationID ?? default(int);
            // se o id da publicação for inválido informa o bad request
            if (index >= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = db.Publication.Find(index);
            // se a publicação não existir ou, se for um publicação por aceitar e o utilizador não é um admin,
            // redireciona para a primeira vista da listagem de publicações
            if (model == null || (!User.IsInRole("admin") && !model.Accepted))
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }



        // GET: Publications/Unaccepted
        /// <summary>
        /// 
        /// Procura pelas publicações por aceitar e apresenta
        /// 
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "admin")]
        public ActionResult Unaccepted()
        {
            return View(db.Publication.Where(x => !x.Accepted).OrderByDescending(p => p.CreatedIn).ToList());
        }

        // POST: Publications/Vote/
        /// <summary>
        /// 
        /// Executa o voto numa votação
        /// 
        /// </summary>
        /// <param name="optionID"></param>
        /// <param name="pollID"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Vote(int optionID, int pollID)
        {
            // Apenas os sócios, ou em caso de votações autorizadas também os associados, podem votar
            if (User.IsInRole("partner") || (db.Poll.Find(pollID).IsInclusive && User.IsInRole("associated")))
            {
                // verifica se existe a relações entre a opção de voto e a votação
                if (!db.Vote.Where(x => x.Option.PollFK.Equals(pollID)).Where(x => x.User.UserName.Equals(User.Identity.Name)).Any())
                {
                    // guarda o voto
                    Vote vote = new Vote { OptionFK = optionID, UserFK = User.Identity.GetUserId() };
                    db.Vote.Add(vote);
                    db.SaveChanges();
                    // incrementa o atributo da cotagem de votos na opção para estatisticas
                    Option option = db.Option.Find(optionID);
                    option.Count++;
                    db.Entry(option).State = EntityState.Modified;
                    db.SaveChanges();
                    // regista a ação do utilizador
                    Log(String.Format("Votou no questionário: {0}", db.Poll.Find(pollID).Matter));
                    return Json(new { result = true, msg = "Voto inserido com sucesso." });
                }
                else
                {
                    return Json(new { result = false, msg = "Já tinha votado anteriormente." });
                }
            }
            else
            {
                return Json(new { result = false, msg = "Não autorizado." });
            }

        }

        // POST: Publications/Comment/
        /// <summary>
        /// 
        /// Comenta numa publicação
        /// 
        /// </summary>
        /// <param name="text"></param>
        /// <param name="publicationID"></param>
        /// <param name="publicationName"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "partner")]
        public JsonResult Comment(String text, int publicationID, String publicationName)
        {
            try
            {
                // guarda o comentário
                Reply reply = new Reply { Content = text, Hour = DateTime.Now, IsVisible = true, PublicationFK = publicationID, UserFK = User.Identity.GetUserId() };
                db.Reply.Add(reply);
                db.SaveChanges();
                // guarda a ação  do utilizador
                Log(String.Format("Comentou ( {0} ) na publicação: {1}", text, publicationName));
                return Json(new { result = true, publication = publicationID, hour = reply.Hour.ToString("dd MMM yyyy - hh:mm"), user = db.Users.Find(User.Identity.GetUserId()).Name.ToString() });
            }
            catch (Exception ex)
            {
                Console.Write(ex);
                return Json(new { result = false, msg = "Ocorreu um erro, não foi possível adicionar o seu comentário. Por favor tente mais tarde." });
            }
        }

        // POST: Publications/Censor/5
        /// <summary>
        /// 
        /// Censura ou retira a censura de um comentário
        /// 
        /// </summary>
        /// <param name="replyID"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "collaborator")]
        public JsonResult Censor(int replyID)
        {
            try
            {
                // procura o comentário
                Reply r = db.Reply.Find(replyID);
                // se estiver visível coloca a invisivel e vice-versa
                r.IsVisible = r.IsVisible == true ? false : true;
                db.Entry(r).State = EntityState.Modified;
                db.SaveChanges();
                // regista a ação do utilizador
                Log(String.Format("Censurou o comentário ( {0} ) de {1} na publicação: {2}", r.Content, r.User.Name, r.Publication.Name));
                return Json(new { result = true, msg = "A censura foi realizada com sucesso. Atualize a página se pretender retroceder." });
            }
            catch (Exception ex)
            {
                Console.Write(ex);
                return Json(new { result = false, msg = "Ocorreu um erro, não foi possível censurar o comentário. Por favor tente mais tarde." });
            }
        }

        // POST: Publications/Censor/5
        /// <summary>
        /// 
        /// Encerra a votação
        /// 
        /// </summary>
        /// <param name="pollID"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "collaborator")]

Project/Views/Publications/Create.cshtml
@model Project.Models.PublicationCreateViewModel

<script src="@Url.Content("~/Scripts/tinymce/tinymce.min.js")"></script>

@using (Html.BeginForm("Create", "Publications", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-sm-8">
            <h2>Nova Publicação</h2>
        </div>
        <div class="col-sm-4" style="padding-top:3%;padding-bottom:2%;">
            <div class="pull-right">
                <button type="submit" value="Create" class="btn btn-primary">Criar</button>
                @Html.ActionLink("Voltar às publicações", "Index", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-8 col-md-10">
            <div class="container-fluid row">
                <div class="col-xs-12">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                </div>

                @* Title *@
                <div class="col-xs-12">
                    <div class="row">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3 text-right", id="crtTitle" })
                        <div class="col-md-9">
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                @* Image *@
                <div class="col-xs-12">
                    <div class="row">
                        <label class="control-label col-md-3 text-right">Imagem da Publicação</label>
                        <div class="col-md-9">
                            <img class="img-responsive" style="max-height:400px;" id="imgPreview" src="" hidden />
                            @Html.TextBox("file", "", new { type = "file", onchange = "loadFile(event)" })
                        </div>
                    </div>
                </div>
                @* Resume *@
                <div class="col-xs-12">
                    <div class="row">
                        @Html.LabelFor(model => model.Resume, htmlAttributes: new { @class = "control-label col-md-3 text-right" })
                        <div class="col-md-9">
                            @Html.TextAreaFor(model => model.Resume, new { @class = "form-control" , @style = "height:200px" })
                            @Html.ValidationMessageFor(model => model.Resume, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                @* Description *@
                <div class="col-xs-12">
                    <div class="row">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3 text-right" })
                        <div class="col-md-9">
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @id="richtext", @style = "height:400px" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <script>tinymce.init({
                        selector: '#richtext',
                        statusbar: false,
                        menubar: false,
                        toolbar: 'fontselect fontsizeselect | bold italic underline | subscript superscript | forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist | hr table link charmap | print preview',
                        plugins: 'link colorpicker textcolor print lists preview hr table charmap',
                        skin: 'lightgray'
                    });
                </script>
                @* EVENT *@
                <div class="col-xs-12">
                    <div class="row">
                        @Html.LabelFor(model => model.IsEvent, htmlAttributes: new { @class = "control-label col-md-3 text-right" })
                        <div class="col-md-9">
                            <label data-toggle="collapse" data-target=".collapseEvent">
                                @Html.CheckBoxFor(model => model.IsEvent, new { @class = "form-control", @style = "width:0;" })
                            </label>
                            @Html.ValidationMessageFor(model => model.IsEvent, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                @* Day *@
                <div class="col-xs-12 collapseEvent collapse">
                    <div class="row">
                        @Html.LabelFor(model => model.Day, htmlAttributes: new { @class = "control-label col-md-3 text-right" })
                        <div class="col-md-9">
                            @Html.TextBoxFor(model => model.Day, new { @class = "form-control", @id= "form_datetime" })
                            @Html.ValidationMessageFor(model => model.Day, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                @* Local *@
                <div class="col-xs-12 collapseEvent collapse">
                    <div class="row">
                        @Html.LabelFor(model => model.Local, htmlAttributes: new { @class = "control-label col-md-3 text-right" })
                        <div class="col-md-9">
                            @Html.TextBoxFor(model => model.Local, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Local, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                @* POLL *@
                <div class="col-xs-12">
                    <div class="row">
                        @Html.LabelFor(model => model.IsPoll, htmlAttributes: new { @class = "control-label col-md-3 text-right" })
                        <div class="col-md-9">
                            <label data-toggle="collapse" data-target=".collapsePoll">
                                @Html.CheckBoxFor(model => model.IsPoll, new { @class = "form-control", @style = "width:0;" })
                            </label>
                            @Html.ValidationMessageFor(model => model.IsPoll, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                @* Matter *@
                <div class="col-xs-12 collapsePoll collapse">
                    <div class="row">
                        @Html.LabelFor(model => model.Matter, htmlAttributes: new { @class = "control-label col-md-3 text-right" })
                        <div class="col-md-9">
                            @Html.TextBoxFor(model => model.Matter, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Matter, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                @* Form *@
                <div class="col-xs-12 collapsePoll collapse">
                    <div class="row">
                        @Html.LabelFor(model => model.LinkToForm, htmlAttributes: new { @class = "col-md-3 text-right" })
                        <div class="col-md-9">
                            @Html.TextBoxFor(model => model.LinkToForm, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.LinkToForm, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                @* IsVisible *@
                <div class="col-xs-12 collapsePoll collapse">
                    <div class="row">
                        @Html.LabelFor(model => model.IsVisible, htmlAttributes: new { @class = "control-label col-md-3 text-right" })
                        <div class="col-md-9">
                            @Html.CheckBoxFor(model => model.IsVisible, new { @class = "form-control", @style = "width:0;" })
                            @Html.ValidationMessageFor(model => model.IsVisible, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                @* IsInclusive *@
                <div class="col-xs-12 collapsePoll collapse">
                    <div class="row">
                        @Html.LabelFor(model => model.IsInclusive, htmlAttributes: new { @class = "control-label col-md-3 text-right" })
                        <div class="col-md-9">
                            @Html.CheckBoxFor(model => model.IsInclusive, new { @class = "form-control", @style = "width:0;" })
                            @Html.ValidationMessageFor(model => model.IsInclusive, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                @* Options *@
                <div class="col-xs-12 collapsePoll collapse">
                    <div class="row">
                        @Html.LabelFor(model => Model.OptionName, htmlAttributes: new { @class = "control-label col-md-3 text-right" })
                        <div class="col-md-9">
                            <div class="row" id="options"></div>
                            <a id="btnAddOption" onclick="addOption()" class="btn btn-default">Adicionar Opção</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-2"></div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>
    $("#form_datetime").datetimepicker({ format: 'yyyy-mm-dd hh:ii' });
    var optionID = 0;
</script>

Project/Views/Publications/Index.cshtml
@model Project.Models.PublicationListViewModel

@{
    ViewBag.Title = "List";
}

<div class="container">
    <div class="pull-right" style="padding-top:3%;padding-bottom:2%;">
        @* Apenas o admin pode aceitar publicações *@
        @if (User.IsInRole("admin"))
            {
            @Html.ActionLink("Pendentes", "Unaccepted", null, new { @class = "btn btn-default" })
        }
        @* apenas os colaboradores podem criar novas publicações *@
        @if (User.IsInRole("collaborator"))
            {
            @Html.ActionLink("Nova Publicação", "Create", null, new { @class = "btn btn-default" })
        }
    </div>
</div>

@if (Model.Header != null)
{
    <div id="myCarousel" class="carousel slide hidden-xs" data-ride="carousel">
        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            @for (var i = 0; i < 4; i++)
                {

                    if (i == 0)
                    {
                    <div class="item active">
                        <a href="@Url.Action("Details", new { publicationID=Model.Header[i].ID})">
                            <img src="~/fonts/@Url.Content(Model.Header[i].Image)" style="height:600px;" class="img-responsive center-block" />
                            <div class="carousel-caption">
                                <h3>@Html.DisplayFor(modelItem => Model.Header[i].Name)</h3>
                            </div>
                        </a>
                    </div>
                }
                else
                {
                    <div class="item text-center">
                        <a href="@Url.Action("Details", new { publicationID=Model.Header[i].ID})">
                            <img src="~/fonts/@Url.Content(Model.Header[i].Image)" style="height:600px;" class="img-responsive center-block" />
                            <div class="carousel-caption">
                                <h3>@Html.DisplayFor(modelItem => Model.Header[i].Name)</h3>
                            </div>
                        </a>
                    </div>
                }
            }
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
        <hr />
}


<div class="row">
    @*PUBLICATION LIST *@
    @foreach (var item in Model.List)
    {
        <div class="col-sm-6 col-lg-4">
            <a href="@Url.Action("Details", new { publicationID=item.ID})">
                <div id="panel@(item.ID)" class="panel panel-primary" style="position:relative; height:300px">
                    @* Image *@
                    @if (item.Image != null)
                    {
                        <script>
                            $("#panel@(item.ID)").css({
                                'background-image': 'url(../../fonts/@Url.Content(item.Image))',
                                'background-size': '100% 100%',
                                'background-repeat': 'no-repeat'
                            });
                        </script>
                    }
                    <div class="well well-sm" style="background-color:rgba(200, 200, 200, 0.6);">
                        <div class="row">
                            <div class="col-xs-2">
                                @* Type *@
                                @if (item.EventFK != null)
                                {<span class="badge" style="background-color:rgb(50, 50, 50);"><i class="text-success glyphicon glyphicon-globe"></i></span>}
                                @if (item.PollFK != null)
                                {<span class="badge" style="background-color:rgb(50, 50, 50);"><i class="text-primary glyphicon glyphicon-list"></i></span>}
                            </div>
                            @* Title *@
                            <div class="col-xs-6 text-center"><h4><b>@Html.DisplayFor(modelItem => item.Name)</b></h4></div>
                            <div class="col-xs-4 text-right">
                                @* Date *@
                                <kbd>@Html.DisplayFor(modelItem => item.CreatedIn)</kbd>
                            </div>
                        </div>
                    </div>

                    @* Text *@
                    @if (item.Resume != null)
                    {
                        string summary = item.Resume.Length > 150 ? item.Resume.ToString().Substring(0, 150) + "..." : item.Resume.ToString();
                        <div class="well well-sm" style="background-color:rgba(0, 0, 0, 0.6);bottom:-20px;position:absolute;"><h6 class="h6 text-justify" style="color:white;">@Html.DisplayFor(modelItem => summary)</h6></div>
                    }
                </div>
            </a>
        </div>
    }
</div>


@* Pagination arrows *@
<div class="row">
    <div class="col-xs-6 text-right">
        @if (Model.HaveLess)
            { <a href="@Url.Action("Page", "Publications", new { i=Model.Index-1 })" class="btn btn-default"><span class="glyphicon glyphicon-chevron-left" aria-label="Left Align" aria-hidden="true"></span></a> }
    </div>
    <div class="col-xs-6">
        @if (Model.HaveMore)
            { <a href="@Url.Action("Page", "Publications", new { i=Model.Index+1 })" class="btn btn-default"><span class="glyphicon glyphicon-chevron-right" aria-label="Right Align" aria-hidden="true"></span></a> }
    </div>
</div>